#!/bin/python
from pathlib import Path

with open(str(Path.home()) + "/.config/i3/config") as config_file:
    for line in config_file.readlines():
        line = line.replace("\n", "").split(" ")
        if line[0] == 'bindsym':
            line = line[1:]

            comment = []
            is_comment = False
            for i in range(0, len(line)):
                if line[i] == '#':
                    is_comment = True
                    comment.append('->')
                    continue

                if is_comment:
                    comment.append(line[i])

            if len(comment) == 0:
                comment = ["->", "???"]
            
            command = line[0] + " " + " ".join(comment)
            print(command)
