#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

setxkbmap us intl

feh --bg-fill --randomize $HOME/Pictures/wallpapers/
# hsetroot -solid "#2e3440"
$HOME/.scripts/toggle_polybar.sh
picom &
dunst &

# Put monitor to sleep automatically after 10 minutes of inactivity
xset dpms 0 0 600

# Checking for updates at window manager startup
dunstify --timeout=5000 "Checking for updates..." "$($HOME/.scripts/list_updates_available.sh)"
